### ISSUE TITLE
Unable to "Activate recommended features" during Jetpack setup

### ISSUE THREAD

**Issue by scottsweb** [Automattic/vip-jetpack#26]
When activating the default set of recommended features in Jetpack a console error is thrown:

```
Fetch API cannot load https://site.go-vip.co/wp-json/jetpack/v4/site. Request header field x-wp-nonce is not allowed by Access-Control-Allow-Headers in preflight response.
```

It would seem that the `x-wp-nonce` header is being blocked. I am hoping we can fix it here, or perhaps we need to go make some changes to our nginx configs?

**Comment by nickdaugherty** [comment]
@scottsweb The header problem is a known issues that is being discussed on P2.

**Comment by scottsweb** [comment]
Ok, lets close this for now.
